/**
 * Marlin 3D Printer Firmware
 * Copyright (C) 2016 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (C) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/**
 * Russian
 *
 * LCD Menu Messages
 * See also https://github.com/MarlinFirmware/Marlin/wiki/LCD-Language
 *
 */
#ifndef LANGUAGE_RU_H
#define LANGUAGE_RU_H

#define MAPPER_D0D1                // For Cyrillic
// Define SIMULATE_ROMFONT to see what is seen on the character based display defined in Configuration.h
//#define SIMULATE_ROMFONT
#define DISPLAY_CHARSET_ISO10646_5

#define WELCOME_MSG                         MACHINE_NAME " Готов."
#define MSG_SD_INSERTED                     "Карта вставлена"
#define MSG_SD_REMOVED                      "Карта извлечена"
#define MSG_MAIN                            "Меню"
#define MSG_AUTOSTART                       "Автостарт"
#define MSG_DISABLE_STEPPERS                "Выкл. двигатели"
#define MSG_AUTO_HOME                       "Парковка"
#define MSG_LEVEL_BED_HOMING                "Homing XYZ"
#define MSG_LEVEL_BED_WAITING               "Click to Begin"
#define MSG_LEVEL_BED_DONE                  "Leveling Done!"
#define MSG_LEVEL_BED_CANCEL                "Cancel"
#define MSG_SET_HOME_OFFSETS                "Запомнить парковку"
#define MSG_HOME_OFFSETS_APPLIED            "Offsets applied"
#define MSG_SET_ORIGIN                      "Запомнить ноль"
#define MSG_PREHEAT_PLA                     "Преднагрев PLA"
<<<<<<< HEAD
#define MSG_PREHEAT_PLA_N                   "Греть PLA Сопло "
#define MSG_PREHEAT_PLA_ALL                 "Греть PLA Все"
#define MSG_PREHEAT_PLA_BEDONLY             "Греть PLA Стол"
#define MSG_PREHEAT_PLA_SETTINGS            "Настройки PLA"
#define MSG_PREHEAT_ABS                     "Преднагрев ABS"
#define MSG_PREHEAT_ABS_N                   "Греть ABS Сопло "
#define MSG_PREHEAT_ABS_ALL                 "Греть ABS Все"
#define MSG_PREHEAT_ABS_BEDONLY             "Греть ABS Стол"
#define MSG_PREHEAT_ABS_SETTINGS            "Настройки ABS"
#define MSG_COOLDOWN                        "Охлаждение"
#define MSG_SWITCH_PS_ON                    "Включить Питание"
#define MSG_SWITCH_PS_OFF                   "Отключить Питание"
=======
#define MSG_PREHEAT_PLA0                    "Преднагрев PLA0"
#define MSG_PREHEAT_PLA1                    "Преднагрев PLA1"
#define MSG_PREHEAT_PLA2                    "Преднагрев PLA2"
#define MSG_PREHEAT_PLA012                  "Преднаг. PLA все"
#define MSG_PREHEAT_PLA_BEDONLY             "Пред. PLA кровать"
#define MSG_PREHEAT_PLA_SETTINGS            "Настройки PLA"
#define MSG_PREHEAT_ABS                     "Преднагрев ABS"
#define MSG_PREHEAT_ABS0                    "Преднагрев ABS0"
#define MSG_PREHEAT_ABS1                    "Преднагрев ABS1"
#define MSG_PREHEAT_ABS2                    "Преднагрев ABS2"
#define MSG_PREHEAT_ABS012                  "Преднаг. ABS все "
#define MSG_PREHEAT_ABS_BEDONLY             "Пред. ABS кровать"
#define MSG_PREHEAT_ABS_SETTINGS            "Настройки ABS"
#define MSG_COOLDOWN                        "Охлаждение"
#define MSG_SWITCH_PS_ON                    "Вкл.питание"
#define MSG_SWITCH_PS_OFF                   "Выкл.питание"
>>>>>>> origin/1.0.x
#define MSG_EXTRUDE                         "Экструзия"
#define MSG_RETRACT                         "Втягивание"
#define MSG_MOVE_AXIS                       "Движение по осям"
<<<<<<< HEAD
#define MSG_MOVE_X                          "Движение по X"
#define MSG_MOVE_Y                          "Движение по Y"
#define MSG_MOVE_Z                          "Движение по Z"
#define MSG_MOVE_E                          "Экструдер"
#define MSG_MOVE_01MM                       "Движение XYZ 0.1mm"
#define MSG_MOVE_1MM                        "Движение XYZ 1mm"
#define MSG_MOVE_10MM                       "Движение XY 10mm"
#define MSG_LEVEL_BED                       "Калибровать стол"
#define MSG_SPEED                           "Скорость"
#define MSG_NOZZLE                          LCD_STR_THERMOMETER " Сопло"
#define MSG_BED                             LCD_STR_THERMOMETER " Стол"
#define MSG_FAN_SPEED                       "Кулер"
#define MSG_FLOW                            "Поток"
#define MSG_CONTROL                         "Настройки"
#define MSG_MIN                             LCD_STR_THERMOMETER " Минимум"
#define MSG_MAX                             LCD_STR_THERMOMETER " Максимум"
#define MSG_FACTOR                          LCD_STR_THERMOMETER " Фактор"
#define MSG_AUTOTEMP                        "Автотемпература"
#define MSG_ON                              "Вкл. "
#define MSG_OFF                             "Откл. "
#define MSG_PID_P                           "PID-P"
#define MSG_PID_I                           "PID-I"
#define MSG_PID_D                           "PID-D"
#define MSG_PID_C                           "PID-C"
#define MSG_ACC                             "Acc"
#define MSG_VXY_JERK                        "Vxy-jerk"
#define MSG_VZ_JERK                         "Vz-jerk"
#define MSG_VE_JERK                         "Ve-jerk"
#define MSG_VMAX                            "Vmax "
#define MSG_X                               "X"
#define MSG_Y                               "Y"
#define MSG_Z                               "Z"
#define MSG_E                               "E"
#define MSG_VMIN                            "Vmin"
#define MSG_VTRAV_MIN                       "VTrav min"
#define MSG_AMAX                            "Amax"
#define MSG_A_RETRACT                       "A-втягивание"
#define MSG_XSTEPS                          "X шаг/мм"
#define MSG_YSTEPS                          "Y шаг/мм"
#define MSG_ZSTEPS                          "Z шаг/мм"
#define MSG_ESTEPS                          "E шаг/мм"
#define MSG_TEMPERATURE                     "Температура"
#define MSG_MOTION                          "Механика"
#define MSG_VOLUMETRIC                      "Пруток"
#define MSG_VOLUMETRIC_ENABLED              "E в mm3"
#define MSG_FILAMENT_DIAM                   "Диаметр прутка"
#define MSG_CONTRAST                        "Контраст LCD"
#define MSG_STORE_EPROM                     "Сохранить в EEPROM"
#define MSG_LOAD_EPROM                      "Считать из EEPROM"
#define MSG_RESTORE_FAILSAFE                "Сброс EEPROM"
#define MSG_REFRESH                         "Обновить"
#define MSG_WATCH                           "Обзор"
#define MSG_PREPARE                         "Действия"
#define MSG_TUNE                            "Настройки"
#define MSG_PAUSE_PRINT                     "Пауза печати"
#define MSG_RESUME_PRINT                    "Продолжить печать"
=======
#define MSG_MOVE_X                          "Движение оси X"
#define MSG_MOVE_Y                          "Движение оси Y"
#define MSG_MOVE_Z                          "Движение оси Z"
#define MSG_MOVE_E                          "Экструдер"
#define MSG_MOVE_E1                         "Экструдер2"
#define MSG_MOVE_E2                         "Экструдер3"
#define MSG_MOVE_01MM                       "Сдвиг на 0.1мм"
#define MSG_MOVE_1MM                        "Сдвиг на 1мм"
#define MSG_MOVE_10MM                       "Сдвиг на 10мм"
#define MSG_SPEED                           "Скорость:"
#define MSG_NOZZLE                          "\002 Фильера:"
#define MSG_NOZZLE1                         "\002 Фильера2:"
#define MSG_NOZZLE2                         "\002 Фильера3:"
#define MSG_BED                             "\002 Кровать:"
#define MSG_FAN_SPEED                       "Кулер:"
#define MSG_FLOW                            "Поток:"
#define MSG_FLOW0                           " Поток0:"
#define MSG_FLOW1                           " Поток1:"
#define MSG_FLOW2                           " Поток2:"
#define MSG_CONTROL                         "Настройки \003"
#define MSG_MIN                             "\002 Минимум:"
#define MSG_MAX                             "\002 Максимум:"
#define MSG_FACTOR                          "\002 Фактор:"
#define MSG_AUTOTEMP                        "Автотемп.:"
#define MSG_ON                              "Вкл. "
#define MSG_OFF                             "Выкл. "
#define MSG_PID_P                           "PID-P: "
#define MSG_PID_I                           "PID-I: "
#define MSG_PID_D                           "PID-D: "
#define MSG_PID_C                           "PID-C: "
#define MSG_ACC                             "Уск:"
#define MSG_VXY_JERK                        "Vxy-jerk: "
#define MSG_VZ_JERK                         "Vz-jerk"
#define MSG_VE_JERK                         "Ve-jerk"
#define MSG_VMAX                            "Vmax "
#define MSG_X                               "x:"
#define MSG_Y                               "y:"
#define MSG_Z                               "z:"
#define MSG_E                               "e:"
#define MSG_VMIN                            "Vmin:"
#define MSG_VTRAV_MIN                       "VTrav min:"
#define MSG_AMAX                            "Amax "
#define MSG_A_RETRACT                       "A-retract:"
#define MSG_XSTEPS                          "X шаг/mm:"
#define MSG_YSTEPS                          "Y шаг/mm:"
#define MSG_ZSTEPS                          "Z шаг/mm:"
#define MSG_ESTEPS                          "E шаг/mm:"
#define MSG_TEMPERATURE                     "Температура     \x7E"
#define MSG_MOTION                          "Скорости        \x7E"
#define MSG_VOLUMETRIC                      "Материал"
#define MSG_VOLUMETRIC_ENABLED		        "E in mm3"
#define MSG_FILAMENT_SIZE_EXTRUDER_0        "Диам.Мат.  1"
#define MSG_FILAMENT_SIZE_EXTRUDER_1        "Диам.Мат.  2"
#define MSG_FILAMENT_SIZE_EXTRUDER_2        "Диам.Мат.  3"
#define MSG_CONTRAST                        "Контраст LCD"
#define MSG_STORE_EPROM                     "Сохранить в EEPROM"
#define MSG_LOAD_EPROM                      "Загруз. из EEPROM"
#define MSG_RESTORE_FAILSAFE                "Сброс настроек"
#define MSG_REFRESH                         "\004Обновить"
#define MSG_WATCH                           "Обзор           \003"
#define MSG_PREPARE                         "Действия        \x7E"
#define MSG_TUNE                            "Настройки       \x7E"
#define MSG_PAUSE_PRINT                     "Продолжить печать"
#define MSG_RESUME_PRINT                    "Возобн. печать"
>>>>>>> origin/1.0.x
#define MSG_STOP_PRINT                      "Остановить печать"
#define MSG_CARD_MENU                       "Обзор карты"
#define MSG_NO_CARD                         "Нет карты"
#define MSG_DWELL                           "Сон..."
#define MSG_USERWAIT                        "Ожиданиие"
<<<<<<< HEAD
#define MSG_RESUMING                        "Возобновление..."
#define MSG_PRINT_ABORTED                   "Отмена печати"
#define MSG_NO_MOVE                         "Нет движения."
#define MSG_KILLED                          "УБИТО."
#define MSG_STOPPED                         "ОСТАНОВЛЕНО."
#define MSG_CONTROL_RETRACT                 "Втягивание mm"
#define MSG_CONTROL_RETRACT_SWAP            "Втяг. смены mm"
#define MSG_CONTROL_RETRACTF                "Втягивание V"
#define MSG_CONTROL_RETRACT_ZLIFT           "Втяг. прыжка mm"
#define MSG_CONTROL_RETRACT_RECOVER         "Возврат +mm"
#define MSG_CONTROL_RETRACT_RECOVER_SWAP    "Возврат смены +mm"
#define MSG_CONTROL_RETRACT_RECOVERF        "Возврат  V"
#define MSG_AUTORETRACT                     "Авто Втягивание"
#define MSG_FILAMENTCHANGE                  "Смена прутка"
#define MSG_INIT_SDCARD                     "Иниц. карту"
#define MSG_CNG_SDCARD                      "Сменить карту"
#define MSG_ZPROBE_OUT                      "Z датчик вне стола"
#define MSG_YX_UNHOMED                      "Паркуй X/Y перед Z"
#define MSG_ZPROBE_ZOFFSET                  "Смещение Z"
=======
#define MSG_RESUMING                        "Продолжение печати"
#define MSG_PRINT_ABORTED                   "Печать прервана"
#define MSG_NO_MOVE                         "Нет движения."
#define MSG_KILLED                          "УБИТО."
#define MSG_STOPPED                         "ОСТАНОВЛЕНО."
#define MSG_CONTROL_RETRACT                 "Откат mm:"
#define MSG_CONTROL_RETRACT_SWAP            "своп Откат mm:"
#define MSG_CONTROL_RETRACTF                "Откат  V:"
#define MSG_CONTROL_RETRACT_ZLIFT           "Прыжок mm:"
#define MSG_CONTROL_RETRACT_RECOVER         "Возврат +mm:"
#define MSG_CONTROL_RETRACT_RECOVER_SWAP    "своп Возврат +mm:"
#define MSG_CONTROL_RETRACT_RECOVERF        "Возврат  V:"
#define MSG_AUTORETRACT                     "АвтоОткат:"
#define MSG_FILAMENTCHANGE                  "Сменить материал"
#define MSG_INIT_SDCARD                     "Иниц. карту"
#define MSG_CNG_SDCARD                      "Сменить карту"
#define MSG_ZPROBE_OUT                      "Z probe out. bed"
#define MSG_POSITION_UNKNOWN                "Home X/Y before Z"
#define MSG_ZPROBE_ZOFFSET                  "Z отступ"
>>>>>>> origin/1.0.x
#define MSG_BABYSTEP_X                      "Babystep X"
#define MSG_BABYSTEP_Y                      "Babystep Y"
#define MSG_BABYSTEP_Z                      "Babystep Z"
#define MSG_ENDSTOP_ABORT                   "Сработал концевик"
#define MSG_HEATING_FAILED_LCD              "Разогрев не удался"
#define MSG_ERR_REDUNDANT_TEMP              "Ошибка:Слишком горячо"
#define MSG_THERMAL_RUNAWAY                 "THERMAL RUNAWAY"
#define MSG_ERR_MAXTEMP                     "Ошибка: Т макс."
#define MSG_ERR_MINTEMP                     "Ошибка: Т мин."
#define MSG_ERR_MAXTEMP_BED                 "Ошибка:Т макс.стол"
#define MSG_ERR_MINTEMP_BED                 "Ошибка:Т мин.стол"
#define MSG_END_HOUR                        "часов"
#define MSG_END_MINUTE                      "минут"
#define MSG_HEATING                         "Нагреваю сопло..."
#define MSG_HEATING_COMPLETE                "Нагрев выполнен"
#define MSG_BED_HEATING                     "Нагреваю стол"
#define MSG_BED_DONE                        "Стол разогрет"

#define MSG_DELTA_CALIBRATE                 "Калибровка Delta"
#define MSG_DELTA_CALIBRATE_X               "Калибровать X"
#define MSG_DELTA_CALIBRATE_Y               "Калибровать Y"
#define MSG_DELTA_CALIBRATE_Z               "Калибровать Z"
#define MSG_DELTA_CALIBRATE_CENTER          "Калибровать Center"

#endif // LANGUAGE_RU_H
